
#!~/anaconda3/envs/testNE/bin/Rscript

### 00README 
# this is to perform sanity check on rds generated by rui

# Load necessary libraries
library(Matrix)
library(data.table)
library(dplyr)


###### Setup ==============================================================================
CMC_dir <- "/space/scratch/rui_sz_project/PavlabSZProject/data/data_processed/CMC/Raw"
multi_dir <- "/space/scratch/rui_sz_project/PavlabSZProject/data/data_processed/SZBDMulti-Seq/Raw"

CMC_patients   <- readRDS("/space/scratch/rui_sz_project/PavlabSZProject/data/data_processed/CMC/CMC-patients.rds")
multi_patients <- readRDS("/space/scratch/rui_sz_project/PavlabSZProject/data/data_processed/SZBDMulti-Seq/SZBDMulti-Seq-patients.rds")

cellTypes = c("Ast" , "Exc" , "Inh", "Mic" , "Oli", "Opc")

###### sanity check ==============================================================================
for (cellType in cellTypes) {
    message(cellType)
  fileCMC   = readRDS (list.files(path = CMC_dir, pattern = paste0(cellType, ".*\\.rds$"), full.names = TRUE))
  fileMulti = readRDS (list.files(path = multi_dir, pattern = paste0(cellType, ".*\\.rds$"), full.names = TRUE))
  
  if (!(all(colnames(fileCMC$expr) == rownames(fileCMC$meta)) && 
        all(fileCMC$meta$patientID %in% CMC_patients$patientID) &&
        all(colnames(fileMulti$expr) == rownames(fileMulti$meta)) && 
        all(fileMulti$meta$patientID %in% multi_patients$patientID))) {
    
    stop("Error: One or more conditions are not met. Please check the following:
        1. Column names of fileCMC$expr should match rownames of fileCMC$meta.
        2. All patientIDs in fileCMC$meta must be present in CMC_patients.
        3. Column names of fileMulti$expr should match rownames of fileMulti$meta.
        4. All patientIDs in fileMulti$meta must be present in multi_patients.")
    
  } else {
    print("All conditions are met successfully.")
  }
}


